//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dnevnik
{
    using System;
    using System.Collections.Generic;
    
    public partial class userK
    {
        public int id_user { get; set; }
        public string imya { get; set; }
        public string familia { get; set; }
        public string login { get; set; }
        public string parol { get; set; }
        public Nullable<int> id_role { get; set; }
    
        public virtual roleK roleK { get; set; }
    }
}
